name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: "obter código"
        uses: actions/checkout@v4.2.2
      - name: "executar o docker login"
        uses: docker/login-action@v3.4.0
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "executar o docker build e push"
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: victorbcassis/fake-shop-main:lastest
      - run: echo "enviar a imagem docker para o docker hub"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "obter código"
      - run: echo "configurar o kubeconfig"
      - run: echo "executar o apply"
